/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicationsIndexRouteImport } from './routes/publications/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as ContactusIndexRouteImport } from './routes/contactus/index'
import { Route as AboutusIndexRouteImport } from './routes/aboutus/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactusIndexRoute = ContactusIndexRouteImport.update({
  id: '/contactus/',
  path: '/contactus/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutusIndexRoute = AboutusIndexRouteImport.update({
  id: '/aboutus/',
  path: '/aboutus/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/news/$slug': typeof NewsSlugRoute
  '/aboutus': typeof AboutusIndexRoute
  '/contactus': typeof ContactusIndexRoute
  '/news': typeof NewsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/people': typeof PeopleIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/publications': typeof PublicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/news/$slug': typeof NewsSlugRoute
  '/aboutus': typeof AboutusIndexRoute
  '/contactus': typeof ContactusIndexRoute
  '/news': typeof NewsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/people': typeof PeopleIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/publications': typeof PublicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/news/$slug': typeof NewsSlugRoute
  '/aboutus/': typeof AboutusIndexRoute
  '/contactus/': typeof ContactusIndexRoute
  '/news/': typeof NewsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/news/$slug'
    | '/aboutus'
    | '/contactus'
    | '/news'
    | '/partners'
    | '/people'
    | '/projects'
    | '/publications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/news/$slug'
    | '/aboutus'
    | '/contactus'
    | '/news'
    | '/partners'
    | '/people'
    | '/projects'
    | '/publications'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/news/$slug'
    | '/aboutus/'
    | '/contactus/'
    | '/news/'
    | '/partners/'
    | '/people/'
    | '/projects/'
    | '/publications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  NewsSlugRoute: typeof NewsSlugRoute
  AboutusIndexRoute: typeof AboutusIndexRoute
  ContactusIndexRoute: typeof ContactusIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactus/': {
      id: '/contactus/'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutus/': {
      id: '/aboutus/'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  NewsSlugRoute: NewsSlugRoute,
  AboutusIndexRoute: AboutusIndexRoute,
  ContactusIndexRoute: ContactusIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
